### ISSUE TITLE
JPA notwendig?

### ISSUE THREAD

**Issue by svefeh** [moverath/eventory#5]
Beim aufsetzen der Datenbank mit Liquibase ist mir aufgefallen, dass unser Datenmodell nicht so wahnsinnig komplex ist. Im Gegenteil, ich habe eher den Eindruck, dass die Verwendung von JPA die Komplexität erhöht. Spricht etwas gegen etwas gegen die Verwendung von JDBC?

**Comment by moverath** [comment]
Hi Sven,
Ich will mich in dem Projekt mit JPA auseinandersetzen deshalb verwende ich
es :-)
Am 25.02.2015 07:51 schrieb "Sven" notifications@github.com:

**Comment by svefeh** [comment]
Okay kann man machen! :)
